# Generated by Django 6.0.1 on 2026-01-20 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('nombre_suplente_1', models.CharField(blank=True, max_length=100)),
                ('nombre_suplente_2', models.CharField(blank=True, max_length=100)),
                ('puntos_bonificacion', models.IntegerField(default=0)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dirigente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_gestionado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField()),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('suspendido_definitivemente', models.BooleanField(default=False, help_text='Expulsado del campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('BARRA', 'Mal comportamiento de Barra'), ('ROJA', 'Tarjeta Roja ($)'), ('UNIF', 'Mala Uniformación'), ('GRAD', 'Uso indebido de graderío'), ('OTRO', 'Otra sanción')], max_length=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('F1', 'Fase 1 (Todos vs Todos)'), ('8VOS', 'Octavos'), ('4TOS', 'Cuartos'), ('SEMI', 'Semifinal'), ('FIN', 'Final')], default='F1', max_length=10)),
                ('goles_a', models.PositiveIntegerField(default=0)),
                ('goles_b', models.PositiveIntegerField(default=0)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PROG', 'Programado'), ('JUG', 'Finalizado'), ('SUS', 'Suspendido'), ('WO', 'Walkover (No Asistió)')], default='PROG', max_length=4)),
                ('equipo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo')),
                ('equipo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='core.equipo')),
                ('ganador_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganados_wo', to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOL', 'Gol'), ('TA', 'Tarjeta Amarilla'), ('TR', 'Tarjeta Roja Directa'), ('DA', 'Doble Amarilla')], max_length=4)),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ORG', 'Organizador (Dueño del Torneo)'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo')], default='DIR', max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('inscripcion_abierta', models.BooleanField(default=True)),
                ('inicio_inscripcion_jugadores', models.DateField(verbose_name='Inicio Inscripción Jugadores')),
                ('fin_inscripcion_jugadores', models.DateField(verbose_name='Cierre Inscripción Jugadores')),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.torneo'),
        ),
    ]
