# Generated by Django 6.0.1 on 2026-01-20 02:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='goles_a',
            new_name='goles_local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='goles_b',
            new_name='goles_visita',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='dirigente_usuario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='suspendido_definitivemente',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_a',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_b',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='fin_inscripcion_jugadores',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='inicio_inscripcion_jugadores',
        ),
        migrations.AddField(
            model_name='detallepartido',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de sanción'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='dirigente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_dirigido', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='expulsado_torneo',
            field=models.BooleanField(default=False, verbose_name='Excluido del Campeonato'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='rojas_directas_acumuladas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multa',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partido'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='core.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_visita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='core.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_limite_inscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite para Dirigentes'),
        ),
        migrations.AlterField(
            model_name='detallepartido',
            name='tipo',
            field=models.CharField(choices=[('ASIS', 'Asistencia (Jugó)'), ('GOL', 'Gol'), ('TA', 'Tarjeta Amarilla'), ('TR', 'Roja Directa'), ('DA', 'Doble Amarilla'), ('AZUL', 'Mal Uniformado'), ('EBRI', 'Estado Etílico')], max_length=4),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_suplente_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suplente 1'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_suplente_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suplente 2'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntos_bonificacion',
            field=models.IntegerField(default=0, verbose_name='Puntos de Bonificación'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='motivo',
            field=models.CharField(choices=[('BARRA', 'Barra ($5.00)'), ('VEST', 'Graderío/Vestimenta ($2.50)'), ('OTRO', 'Otra Sanción')], max_length=5),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROG', 'Programado'), ('JUG', 'Finalizado'), ('WO', 'Walkover (No Asistió)')], default='PROG', max_length=4),
        ),
        migrations.AlterField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('F1', 'Fase 1 (Todos vs Todos)'), ('F2', 'Etapa Final')], default='F1', max_length=5),
        ),
        migrations.AlterField(
            model_name='partido',
            name='ganador_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ORG', 'Organizador'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo')], default='DIR', max_length=3),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='inscripcion_abierta',
            field=models.BooleanField(default=True, verbose_name='¿Inscripción Habilitada?'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado por Organizador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.equipo')),
            ],
        ),
    ]
