# Generated by Django 6.0.1 on 2026-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_goles_a_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cancha',
            field=models.CharField(default='Cancha Principal', max_length=100, verbose_name='Lugar del Encuentro'),
        ),
    ]
