# Generated by Django 6.0.1 on 2026-01-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partido_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepartido',
            name='minuto',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detallepartido',
            name='tipo',
            field=models.CharField(choices=[('GOL', '⚽ Gol'), ('ASIS', '✅ Asistencia (Jugó el partido)'), ('TA', '🟨 Tarjeta Amarilla'), ('TR', '🟥 Roja Directa'), ('DA', '🟨🟨 Doble Amarilla (Expulsión)'), ('AZUL', '👕 Mal Uniformado'), ('EBRI', '🍺 Estado Etílico')], max_length=5),
        ),
    ]
