# Generated by Django 6.0.1 on 2026-01-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detallepartido_minuto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='numero_fecha',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Fecha/Jornada'),
        ),
    ]
