# Generated by Django 6.0.1 on 2026-01-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partido_numero_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='informe_arbitro',
            field=models.TextField(blank=True, null=True, verbose_name='Informe Arbitral'),
        ),
        migrations.AddField(
            model_name='partido',
            name='informe_vocal',
            field=models.TextField(blank=True, null=True, verbose_name='Informe del Vocal'),
        ),
        migrations.AddField(
            model_name='partido',
            name='validado_local',
            field=models.BooleanField(default=False, verbose_name='Firma Dirigente Local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='validado_visita',
            field=models.BooleanField(default=False, verbose_name='Firma Dirigente Visita'),
        ),
    ]
