# Generated by Django 6.0.1 on 2026-01-21 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partido_informe_arbitro_partido_informe_vocal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='pagada',
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Ya fue pagada?'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas_recibidas', to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='multa',
            name='motivo',
            field=models.CharField(max_length=200, verbose_name='Motivo de la Multa'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='partido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='core.partido'),
            preserve_default=False,
        ),
    ]
