# Generated by Django 6.0.1 on 2026-01-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_multa_descripcion_remove_multa_pagada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='grupo_fase2',
            field=models.CharField(choices=[('A', 'Grupo A (Impares)'), ('B', 'Grupo B (Pares)'), ('N', 'Ninguno (Fase 1)')], default='N', max_length=1, verbose_name='Grupo Fase 2'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('F1', 'Fase 1 (Todos vs Todos)'), ('F2', 'Fase 2 (Grupos A/B)'), ('4TOS', 'Cuartos de Final'), ('SEMI', 'Semifinal'), ('FINAL', 'Final')], default='F1', max_length=5),
        ),
    ]
