# Generated by Django 6.0.1 on 2026-01-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipo_grupo_fase2_alter_partido_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ORG', 'Organizador'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo'), ('FAN', 'Aficionado / Espectador')], default='FAN', max_length=3),
        ),
    ]
