# Generated by Django 6.0.1 on 2026-01-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
