# Generated by Django 6.0.1 on 2026-01-22 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pago_observacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: GOLAZO2026', max_length=20, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Monto en $ a descontar', max_digits=5)),
                ('tipo', models.CharField(choices=[('CANCHA', 'Alquiler de Cancha'), ('TORNEO', 'Inscripción de Campeonato')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('limite_usos', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para ilimitado', null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado_inscripcion',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Aprobación'), ('APROBADO', '✅ Aprobado'), ('RECHAZADO', '❌ Rechazado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='detallepartido',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepartido',
            name='tipo',
            field=models.CharField(choices=[('GOL', '⚽ Gol'), ('ASIS', '✅ Asistencia'), ('TA', '🟨 Amarilla'), ('TR', '🟥 Roja'), ('DA', '🟨🟨 Doble A.'), ('AZUL', '👕 Uniforme'), ('EBRI', '🍺 Ebrio')], max_length=5),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='grupo_fase2',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('N', 'Ninguno')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_suplente_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_suplente_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntos_bonificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='expulsado_torneo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multa',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multa',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='cancha',
            field=models.CharField(default='Cancha Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PROG', 'Programado'), ('JUG', 'Finalizado'), ('WO', 'Walkover')], default='PROG', max_length=4),
        ),
        migrations.AlterField(
            model_name='partido',
            name='etapa',
            field=models.CharField(choices=[('F1', 'Fase 1'), ('F2', 'Fase 2'), ('4TOS', 'Cuartos'), ('SEMI', 'Semifinal'), ('FINAL', 'Final')], default='F1', max_length=5),
        ),
        migrations.AlterField(
            model_name='partido',
            name='informe_arbitro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='informe_vocal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='numero_fecha',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partido',
            name='validado_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='validado_visita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ORG', 'Organizador'), ('VOC', 'Vocal de Mesa'), ('DIR', 'Dirigente de Equipo'), ('FAN', 'Aficionado / Cliente')], default='FAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_limite_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pagado', models.BooleanField(default=False)),
                ('es_torneo', models.BooleanField(default=False, verbose_name='Bloqueo por Torneo')),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cupon')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
