# Generated by Django 6.0.1 on 2026-01-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cupon_equipo_estado_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacancha',
            name='partido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_bloqueo', to='core.partido'),
        ),
    ]
