# Generated by Django 6.0.1 on 2026-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reservacancha_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='monto_reembolso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Inscripción Pagada'),
        ),
        migrations.AddField(
            model_name='reservacancha',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', '✅ Activa'), ('CANCELADA', '🚫 Cancelada')], default='ACTIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='reservacancha',
            name='monto_reembolso',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero devuelto tras cancelación', max_digits=10),
        ),
    ]
