# Generated by Django 6.0.1 on 2026-01-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_equipo_monto_reembolso_equipo_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='costo_amarilla',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Multa Amarilla ($)'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='costo_roja',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Multa Roja ($)'),
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'Tarjeta Amarilla'), ('ROJA', 'Tarjeta Roja'), ('ADMIN', 'Sanción Administrativa')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('pagada', models.BooleanField(default=False, verbose_name='¿Multa Pagada?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='core.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jugador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partido')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo')),
            ],
        ),
    ]
