# Generated by Django 5.2.10 on 2026-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_torneo_costo_amarilla_torneo_costo_roja_sancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('precio_hora_cancha', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
