# Generated by Django 6.0.1 on 2026-02-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacancha',
            name='monto_reembolso',
        ),
        migrations.AlterField(
            model_name='reservacancha',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('ACTIVA', '✅ Confirmada'), ('CANCELADA', '🚫 Cancelada')], default='PENDIENTE', max_length=15),
        ),
    ]
